server:
  port: 8081
spring:
  application:
    name: backend-config-service
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/X-rdo/mingeso_pep2
          search-paths: "config-data"